### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/html-hello-bootstrap#1]
# Revisión - APROBADO :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- ¡Haz hecho un buen trabajo entregándolo tan pronto y tan bien resuelto. Felicidades @Meryalvhe   !
## Estilo de código y limpieza
- ¡Bien hecho! :smiley_cat:
## Mejores prácticas/comentarios
- Recuerda a la hora de crear el proyecto poner tu nombre para luego poder encontrarlo fácilmente entre todos los repositorios de los alumnos de 4GeeksAcademy. Tendría que quedar algo así como `4GeeksAcademy/Meryalvhe-Instagram-Feed-con-Bootstrap`
- Estás utilizando múltiples elementos con el mismo ID (pic). Los IDs deben ser únicos en un documento HTML. Considera cambiarlos a clases si necesitas aplicar estilos similares a varios elementos.
- Es una buena práctica de codificación mantener un estilo consistente y legible en tu código CSS mediante la correcta indentación y espaciado. 
![Captura de pantalla de 2024-03-08 12-43-03](https://github.com/4GeeksAcademy/html-hello-bootstrap/assets/139759297/664e1d5a-1d10-4d28-bbbf-73dddade13d8) :thumbsdown:

![Captura de pantalla de 2024-03-08 12-43-20](https://github.com/4GeeksAcademy/html-hello-bootstrap/assets/139759297/4805f039-4156-4287-af79-36d3ce470116) :thumbsup:

**Comment by Meryalvhe** [comment]
Muchas gracias @EduardoHernandezGuzman me lo anoto todo para tenerlo en cuenta.

**Comment by EduardoHernandezGuzman** [comment]
Muy buen trabajo!!! A por el siguiente proyecto!!!
